name: "FibBot Action"
description: "A Rust-based GitHub Action to compute Fibonacci sequences."
inputs:
  enable_fib:
    description: "Enable Fibonacci computation"
    required: true
    default: "true"
  max_threshold:
    description: "Maximum threshold for Fibonacci computation"
    required: true
    default: "100"
  github_token:
    description: "GitHub token for API operations"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_ENABLE_FIB: ${{ inputs.enable_fib }}
    INPUT_MAX_THRESHOLD: ${{ inputs.max_threshold }}
    GITHUB_TOKEN: ${{ inputs.github_token }}