name: "FibBot Action"
description: "A Rust-based GitHub Action to compute Fibonacci sequences."
inputs:
  enable_fib:
    description: "Enable Fibonacci computation"
    required: true
    default: "true"
  max_threshold:
    description: "Maximum threshold for Fibonacci computation"
    required: true
    default: "100"
  github_token:
    description: "GitHub token for API operations"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout FibBot Repository
      uses: actions/checkout@v4
      with:
        repository: bansikah22/fibbot
        path: fibbot

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Build the Rust Project
      run: |
        cd fibbot
        cargo clean
        cargo build --release --verbose
        ls -lah ./target/release/
        if [ ! -f "./target/release/fibbot" ]; then
          echo "Error: fibbot binary not found!"
          exit 1
        fi
        chmod +x ./target/release/fibbot
      shell: bash

    - name: Run the FibBot Binary
      run: |
        cd fibbot
        ./target/release/fibbot
      shell: bash
      env:
        INPUT_ENABLE_FIB: ${{ inputs.enable_fib }}
        INPUT_MAX_THRESHOLD: ${{ inputs.max_threshold }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
