name: Rust CI Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v4
    - run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
    - name: Build
      run: cargo build --verbose
    - name: Run Test
      run: cargo test --verbose
