name: "Run FibBot Action"
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: rustup install stable
        shell: bash

      - name: Install Dependencies
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          source $HOME/.cargo/env
        shell: bash

      - name: Set up Rust environment
        run: rustup show
        shell: bash

      - name: Run FibBot Action
        uses: ./
        with:
          enable_fib: true
          max_threshold: 1000
