name: "Run FibBot Action"

on: 
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow posting comments on pull requests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -fsSL https://sh.rustup.rs | sh -s -- -y
        shell: bash

      - name: Set up Rust environment
        run: rustup show
        shell: bash

      - name: Run Tests
        run: cargo test
        shell: bash

      - name: Run FibBot Action
        uses: ./
        with:
          enable_fib: true
          max_threshold: 1000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
