name: "Run FibBot Action"
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run FibBot Action
        uses: ./ 
        with:
          enable_fib: true
          max_threshold: 1000
