name: Test and Run FibBot

on: [pull_request]

permissions:
  contents: read  # Explicitly set contents to read
  issues: write  # Allow writing to issues (including PRs)
  pull-requests: write  # Allow posting comments on PRs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -fsSL https://sh.rustup.rs | sh -s -- -y
        shell: bash

      - name: Set up Rust environment
        run: rustup show
        shell: bash

      - name: Run Tests
        run: cargo test
        shell: bash

      - name: Debug GitHub Token
        run: |
          echo "Testing GitHub API with Token..."
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run FibBot Action
        uses: ./
        with:
          enable_fib: true
          max_threshold: 1000
          github-token: ${{ secrets.GITHUB_TOKEN }}  
